export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';

export const LOADING_DETAIL_MOVIE = 'LOADING_DETAIL_MOVIE';
export const GET_DETAIL_MOVIE_SUCESS = 'GET_DETAIL_MOVIE_SUCESS';
export const GET_DATAIL_MOVIE_FAILURE = 'GET_DATAIL_MOVIE_FAILURE';